// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: api/app/v1/app.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	App_TestSign_FullMethodName               = "/api.app.v1.App/TestSign"
	App_EthAuthorize_FullMethodName           = "/api.app.v1.App/EthAuthorize"
	App_AddMessage_FullMethodName             = "/api.app.v1.App/AddMessage"
	App_UserInfo_FullMethodName               = "/api.app.v1.App/UserInfo"
	App_UserBuy_FullMethodName                = "/api.app.v1.App/UserBuy"
	App_UserBuyL_FullMethodName               = "/api.app.v1.App/UserBuyL"
	App_UserRecommend_FullMethodName          = "/api.app.v1.App/UserRecommend"
	App_UserRecommendL_FullMethodName         = "/api.app.v1.App/UserRecommendL"
	App_UserRewardList_FullMethodName         = "/api.app.v1.App/UserRewardList"
	App_UserTeamDepositList_FullMethodName    = "/api.app.v1.App/UserTeamDepositList"
	App_UserLand_FullMethodName               = "/api.app.v1.App/UserLand"
	App_UserStakeGitRewardList_FullMethodName = "/api.app.v1.App/UserStakeGitRewardList"
	App_UserStakeGitStakeList_FullMethodName  = "/api.app.v1.App/UserStakeGitStakeList"
	App_UserBoxList_FullMethodName            = "/api.app.v1.App/UserBoxList"
	App_UserBackList_FullMethodName           = "/api.app.v1.App/UserBackList"
	App_UserMarketSeedList_FullMethodName     = "/api.app.v1.App/UserMarketSeedList"
	App_UserMarketLandList_FullMethodName     = "/api.app.v1.App/UserMarketLandList"
	App_UserMarketPropList_FullMethodName     = "/api.app.v1.App/UserMarketPropList"
	App_UserMarketRentLandList_FullMethodName = "/api.app.v1.App/UserMarketRentLandList"
	App_UserMyMarketList_FullMethodName       = "/api.app.v1.App/UserMyMarketList"
	App_UserNoticeList_FullMethodName         = "/api.app.v1.App/UserNoticeList"
	App_UserStakeRewardList_FullMethodName    = "/api.app.v1.App/UserStakeRewardList"
	App_UserIndexList_FullMethodName          = "/api.app.v1.App/UserIndexList"
	App_UserOrderList_FullMethodName          = "/api.app.v1.App/UserOrderList"
	App_UserOrderListTwo_FullMethodName       = "/api.app.v1.App/UserOrderListTwo"
	App_UserRankList_FullMethodName           = "/api.app.v1.App/UserRankList"
	App_BuyTwo_FullMethodName                 = "/api.app.v1.App/BuyTwo"
	App_Withdraw_FullMethodName               = "/api.app.v1.App/Withdraw"
	App_Exchange_FullMethodName               = "/api.app.v1.App/Exchange"
	App_ToAmount_FullMethodName               = "/api.app.v1.App/ToAmount"
	App_GetLand_FullMethodName                = "/api.app.v1.App/GetLand"
	App_StakeGit_FullMethodName               = "/api.app.v1.App/StakeGit"
	App_BuyBox_FullMethodName                 = "/api.app.v1.App/BuyBox"
	App_OpenBox_FullMethodName                = "/api.app.v1.App/OpenBox"
	App_Sell_FullMethodName                   = "/api.app.v1.App/Sell"
	App_Buy_FullMethodName                    = "/api.app.v1.App/Buy"
	App_RentLand_FullMethodName               = "/api.app.v1.App/RentLand"
	App_LandAddOutRate_FullMethodName         = "/api.app.v1.App/LandAddOutRate"
	App_StakeGet_FullMethodName               = "/api.app.v1.App/StakeGet"
	App_StakeGetPlay_FullMethodName           = "/api.app.v1.App/StakeGetPlay"
	App_LandPlay_FullMethodName               = "/api.app.v1.App/LandPlay"
	App_LandPlayOne_FullMethodName            = "/api.app.v1.App/LandPlayOne"
	App_LandPlayTwo_FullMethodName            = "/api.app.v1.App/LandPlayTwo"
	App_LandPlayThree_FullMethodName          = "/api.app.v1.App/LandPlayThree"
	App_LandPlayFour_FullMethodName           = "/api.app.v1.App/LandPlayFour"
	App_LandPlayFive_FullMethodName           = "/api.app.v1.App/LandPlayFive"
	App_LandPlaySix_FullMethodName            = "/api.app.v1.App/LandPlaySix"
	App_LandPlaySeven_FullMethodName          = "/api.app.v1.App/LandPlaySeven"
	App_SetGiw_FullMethodName                 = "/api.app.v1.App/SetGiw"
	App_SetGit_FullMethodName                 = "/api.app.v1.App/SetGit"
	App_SetLand_FullMethodName                = "/api.app.v1.App/SetLand"
	App_BuyLand_FullMethodName                = "/api.app.v1.App/BuyLand"
	App_GetBuyLand_FullMethodName             = "/api.app.v1.App/GetBuyLand"
	App_BuyLandRecord_FullMethodName          = "/api.app.v1.App/BuyLandRecord"
	App_SetBuyLand_FullMethodName             = "/api.app.v1.App/SetBuyLand"
)

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppClient interface {
	TestSign(ctx context.Context, in *TestSignRequest, opts ...grpc.CallOption) (*TestSignReply, error)
	EthAuthorize(ctx context.Context, in *EthAuthorizeRequest, opts ...grpc.CallOption) (*EthAuthorizeReply, error)
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageReply, error)
	// 用户信息
	UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoReply, error)
	// 认购信息
	UserBuy(ctx context.Context, in *UserBuyRequest, opts ...grpc.CallOption) (*UserBuyReply, error)
	// 认购奖励内容
	UserBuyL(ctx context.Context, in *UserBuyLRequest, opts ...grpc.CallOption) (*UserBuyLReply, error)
	// 直推列表
	UserRecommend(ctx context.Context, in *UserRecommendRequest, opts ...grpc.CallOption) (*UserRecommendReply, error)
	// L1L2L3内容
	UserRecommendL(ctx context.Context, in *UserRecommendLRequest, opts ...grpc.CallOption) (*UserRecommendLReply, error)
	// 粮仓列表
	UserRewardList(ctx context.Context, in *UserRewardListRequest, opts ...grpc.CallOption) (*UserRewardListReply, error)
	UserTeamDepositList(ctx context.Context, in *UserTeamDepositListRequest, opts ...grpc.CallOption) (*UserTeamDepositListReply, error)
	// 土地背包列表
	UserLand(ctx context.Context, in *UserLandRequest, opts ...grpc.CallOption) (*UserLandReply, error)
	// 粮仓列表
	UserStakeGitRewardList(ctx context.Context, in *UserStakeGitRewardListRequest, opts ...grpc.CallOption) (*UserStakeGitRewardListReply, error)
	// 粮仓列表
	UserStakeGitStakeList(ctx context.Context, in *UserStakeGitStakeListRequest, opts ...grpc.CallOption) (*UserStakeGitStakeListReply, error)
	// 盲盒列表
	UserBoxList(ctx context.Context, in *UserBoxListRequest, opts ...grpc.CallOption) (*UserBoxListReply, error)
	// 仓库
	UserBackList(ctx context.Context, in *UserBackListRequest, opts ...grpc.CallOption) (*UserBackListReply, error)
	// 市场 种子
	UserMarketSeedList(ctx context.Context, in *UserMarketSeedListRequest, opts ...grpc.CallOption) (*UserMarketSeedListReply, error)
	// 市场 土地
	UserMarketLandList(ctx context.Context, in *UserMarketLandListRequest, opts ...grpc.CallOption) (*UserMarketLandListReply, error)
	// 市场 道具
	UserMarketPropList(ctx context.Context, in *UserMarketPropListRequest, opts ...grpc.CallOption) (*UserMarketPropListReply, error)
	// 市场 出租
	UserMarketRentLandList(ctx context.Context, in *UserMarketRentLandListRequest, opts ...grpc.CallOption) (*UserMarketRentLandListReply, error)
	// 市场 我的
	UserMyMarketList(ctx context.Context, in *UserMyMarketListRequest, opts ...grpc.CallOption) (*UserMyMarketListReply, error)
	// 通知
	UserNoticeList(ctx context.Context, in *UserNoticeListRequest, opts ...grpc.CallOption) (*UserNoticeListReply, error)
	// 果实放大器 获奖记录
	UserStakeRewardList(ctx context.Context, in *UserStakeRewardListRequest, opts ...grpc.CallOption) (*UserStakeRewardListReply, error)
	// 首页
	UserIndexList(ctx context.Context, in *UserIndexListRequest, opts ...grpc.CallOption) (*UserIndexListReply, error)
	// 排行榜
	UserOrderList(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error)
	UserOrderListTwo(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error)
	UserRankList(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error)
	// 提现
	BuyTwo(ctx context.Context, in *BuyTwoRequest, opts ...grpc.CallOption) (*BuyTwoReply, error)
	// 提现
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawReply, error)
	// 兑换
	Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeReply, error)
	// 转账
	ToAmount(ctx context.Context, in *ToAmountRequest, opts ...grpc.CallOption) (*ToAmountReply, error)
	// 合成土地
	GetLand(ctx context.Context, in *GetLandRequest, opts ...grpc.CallOption) (*GetLandReply, error)
	// 粮仓的质押和赎回
	StakeGit(ctx context.Context, in *StakeGitRequest, opts ...grpc.CallOption) (*StakeGitReply, error)
	// 购买盲盒
	BuyBox(ctx context.Context, in *BuyBoxRequest, opts ...grpc.CallOption) (*BuyBoxReply, error)
	// 开盲盒
	OpenBox(ctx context.Context, in *OpenBoxRequest, opts ...grpc.CallOption) (*OpenBoxReply, error)
	// 出售道具下架道具
	Sell(ctx context.Context, in *SellRequest, opts ...grpc.CallOption) (*SellReply, error)
	// 购买道具
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyReply, error)
	// 出租土地结束出租
	RentLand(ctx context.Context, in *RentLandRequest, opts ...grpc.CallOption) (*RentLandReply, error)
	// 培育
	LandAddOutRate(ctx context.Context, in *LandAddOutRateRequest, opts ...grpc.CallOption) (*LandAddOutRateReply, error)
	// 放大器质押解压
	StakeGet(ctx context.Context, in *StakeGetRequest, opts ...grpc.CallOption) (*StakeGetReply, error)
	// 放大器游戏
	StakeGetPlay(ctx context.Context, in *StakeGetPlayRequest, opts ...grpc.CallOption) (*StakeGetPlayReply, error)
	// 土地替换，收回
	LandPlay(ctx context.Context, in *LandPlayRequest, opts ...grpc.CallOption) (*LandPlayReply, error)
	// 种植和出租的种植
	LandPlayOne(ctx context.Context, in *LandPlayOneRequest, opts ...grpc.CallOption) (*LandPlayOneReply, error)
	// 收成熟植物和出租的
	LandPlayTwo(ctx context.Context, in *LandPlayTwoRequest, opts ...grpc.CallOption) (*LandPlayTwoReply, error)
	// 施肥和出租的
	LandPlayThree(ctx context.Context, in *LandPlayThreeRequest, opts ...grpc.CallOption) (*LandPlayThreeReply, error)
	// 杀虫和出租的
	LandPlayFour(ctx context.Context, in *LandPlayFourRequest, opts ...grpc.CallOption) (*LandPlayFourReply, error)
	// 浇水和出租的
	LandPlayFive(ctx context.Context, in *LandPlayFiveRequest, opts ...grpc.CallOption) (*LandPlayFiveReply, error)
	// 铲子铲别人
	LandPlaySix(ctx context.Context, in *LandPlaySixRequest, opts ...grpc.CallOption) (*LandPlaySixReply, error)
	// 手套偷别人
	LandPlaySeven(ctx context.Context, in *LandPlaySevenRequest, opts ...grpc.CallOption) (*LandPlaySevenReply, error)
	SetGiw(ctx context.Context, in *SetGiwRequest, opts ...grpc.CallOption) (*SetGiwReply, error)
	SetGit(ctx context.Context, in *SetGitRequest, opts ...grpc.CallOption) (*SetGitReply, error)
	SetLand(ctx context.Context, in *SetLandRequest, opts ...grpc.CallOption) (*SetLandReply, error)
	BuyLand(ctx context.Context, in *BuyLandRequest, opts ...grpc.CallOption) (*BuyLandReply, error)
	GetBuyLand(ctx context.Context, in *GetBuyLandRequest, opts ...grpc.CallOption) (*GetBuyLandReply, error)
	BuyLandRecord(ctx context.Context, in *BuyLandRecordRequest, opts ...grpc.CallOption) (*BuyLandRecordReply, error)
	SetBuyLand(ctx context.Context, in *SetBuyLandRequest, opts ...grpc.CallOption) (*SetBuyLandReply, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) TestSign(ctx context.Context, in *TestSignRequest, opts ...grpc.CallOption) (*TestSignReply, error) {
	out := new(TestSignReply)
	err := c.cc.Invoke(ctx, App_TestSign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) EthAuthorize(ctx context.Context, in *EthAuthorizeRequest, opts ...grpc.CallOption) (*EthAuthorizeReply, error) {
	out := new(EthAuthorizeReply)
	err := c.cc.Invoke(ctx, App_EthAuthorize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageReply, error) {
	out := new(AddMessageReply)
	err := c.cc.Invoke(ctx, App_AddMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoReply, error) {
	out := new(UserInfoReply)
	err := c.cc.Invoke(ctx, App_UserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserBuy(ctx context.Context, in *UserBuyRequest, opts ...grpc.CallOption) (*UserBuyReply, error) {
	out := new(UserBuyReply)
	err := c.cc.Invoke(ctx, App_UserBuy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserBuyL(ctx context.Context, in *UserBuyLRequest, opts ...grpc.CallOption) (*UserBuyLReply, error) {
	out := new(UserBuyLReply)
	err := c.cc.Invoke(ctx, App_UserBuyL_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserRecommend(ctx context.Context, in *UserRecommendRequest, opts ...grpc.CallOption) (*UserRecommendReply, error) {
	out := new(UserRecommendReply)
	err := c.cc.Invoke(ctx, App_UserRecommend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserRecommendL(ctx context.Context, in *UserRecommendLRequest, opts ...grpc.CallOption) (*UserRecommendLReply, error) {
	out := new(UserRecommendLReply)
	err := c.cc.Invoke(ctx, App_UserRecommendL_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserRewardList(ctx context.Context, in *UserRewardListRequest, opts ...grpc.CallOption) (*UserRewardListReply, error) {
	out := new(UserRewardListReply)
	err := c.cc.Invoke(ctx, App_UserRewardList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserTeamDepositList(ctx context.Context, in *UserTeamDepositListRequest, opts ...grpc.CallOption) (*UserTeamDepositListReply, error) {
	out := new(UserTeamDepositListReply)
	err := c.cc.Invoke(ctx, App_UserTeamDepositList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserLand(ctx context.Context, in *UserLandRequest, opts ...grpc.CallOption) (*UserLandReply, error) {
	out := new(UserLandReply)
	err := c.cc.Invoke(ctx, App_UserLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserStakeGitRewardList(ctx context.Context, in *UserStakeGitRewardListRequest, opts ...grpc.CallOption) (*UserStakeGitRewardListReply, error) {
	out := new(UserStakeGitRewardListReply)
	err := c.cc.Invoke(ctx, App_UserStakeGitRewardList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserStakeGitStakeList(ctx context.Context, in *UserStakeGitStakeListRequest, opts ...grpc.CallOption) (*UserStakeGitStakeListReply, error) {
	out := new(UserStakeGitStakeListReply)
	err := c.cc.Invoke(ctx, App_UserStakeGitStakeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserBoxList(ctx context.Context, in *UserBoxListRequest, opts ...grpc.CallOption) (*UserBoxListReply, error) {
	out := new(UserBoxListReply)
	err := c.cc.Invoke(ctx, App_UserBoxList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserBackList(ctx context.Context, in *UserBackListRequest, opts ...grpc.CallOption) (*UserBackListReply, error) {
	out := new(UserBackListReply)
	err := c.cc.Invoke(ctx, App_UserBackList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserMarketSeedList(ctx context.Context, in *UserMarketSeedListRequest, opts ...grpc.CallOption) (*UserMarketSeedListReply, error) {
	out := new(UserMarketSeedListReply)
	err := c.cc.Invoke(ctx, App_UserMarketSeedList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserMarketLandList(ctx context.Context, in *UserMarketLandListRequest, opts ...grpc.CallOption) (*UserMarketLandListReply, error) {
	out := new(UserMarketLandListReply)
	err := c.cc.Invoke(ctx, App_UserMarketLandList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserMarketPropList(ctx context.Context, in *UserMarketPropListRequest, opts ...grpc.CallOption) (*UserMarketPropListReply, error) {
	out := new(UserMarketPropListReply)
	err := c.cc.Invoke(ctx, App_UserMarketPropList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserMarketRentLandList(ctx context.Context, in *UserMarketRentLandListRequest, opts ...grpc.CallOption) (*UserMarketRentLandListReply, error) {
	out := new(UserMarketRentLandListReply)
	err := c.cc.Invoke(ctx, App_UserMarketRentLandList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserMyMarketList(ctx context.Context, in *UserMyMarketListRequest, opts ...grpc.CallOption) (*UserMyMarketListReply, error) {
	out := new(UserMyMarketListReply)
	err := c.cc.Invoke(ctx, App_UserMyMarketList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserNoticeList(ctx context.Context, in *UserNoticeListRequest, opts ...grpc.CallOption) (*UserNoticeListReply, error) {
	out := new(UserNoticeListReply)
	err := c.cc.Invoke(ctx, App_UserNoticeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserStakeRewardList(ctx context.Context, in *UserStakeRewardListRequest, opts ...grpc.CallOption) (*UserStakeRewardListReply, error) {
	out := new(UserStakeRewardListReply)
	err := c.cc.Invoke(ctx, App_UserStakeRewardList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserIndexList(ctx context.Context, in *UserIndexListRequest, opts ...grpc.CallOption) (*UserIndexListReply, error) {
	out := new(UserIndexListReply)
	err := c.cc.Invoke(ctx, App_UserIndexList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserOrderList(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error) {
	out := new(UserOrderListReply)
	err := c.cc.Invoke(ctx, App_UserOrderList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserOrderListTwo(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error) {
	out := new(UserOrderListReply)
	err := c.cc.Invoke(ctx, App_UserOrderListTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UserRankList(ctx context.Context, in *UserOrderListRequest, opts ...grpc.CallOption) (*UserOrderListReply, error) {
	out := new(UserOrderListReply)
	err := c.cc.Invoke(ctx, App_UserRankList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) BuyTwo(ctx context.Context, in *BuyTwoRequest, opts ...grpc.CallOption) (*BuyTwoReply, error) {
	out := new(BuyTwoReply)
	err := c.cc.Invoke(ctx, App_BuyTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawReply, error) {
	out := new(WithdrawReply)
	err := c.cc.Invoke(ctx, App_Withdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeReply, error) {
	out := new(ExchangeReply)
	err := c.cc.Invoke(ctx, App_Exchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ToAmount(ctx context.Context, in *ToAmountRequest, opts ...grpc.CallOption) (*ToAmountReply, error) {
	out := new(ToAmountReply)
	err := c.cc.Invoke(ctx, App_ToAmount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetLand(ctx context.Context, in *GetLandRequest, opts ...grpc.CallOption) (*GetLandReply, error) {
	out := new(GetLandReply)
	err := c.cc.Invoke(ctx, App_GetLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) StakeGit(ctx context.Context, in *StakeGitRequest, opts ...grpc.CallOption) (*StakeGitReply, error) {
	out := new(StakeGitReply)
	err := c.cc.Invoke(ctx, App_StakeGit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) BuyBox(ctx context.Context, in *BuyBoxRequest, opts ...grpc.CallOption) (*BuyBoxReply, error) {
	out := new(BuyBoxReply)
	err := c.cc.Invoke(ctx, App_BuyBox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) OpenBox(ctx context.Context, in *OpenBoxRequest, opts ...grpc.CallOption) (*OpenBoxReply, error) {
	out := new(OpenBoxReply)
	err := c.cc.Invoke(ctx, App_OpenBox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Sell(ctx context.Context, in *SellRequest, opts ...grpc.CallOption) (*SellReply, error) {
	out := new(SellReply)
	err := c.cc.Invoke(ctx, App_Sell_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyReply, error) {
	out := new(BuyReply)
	err := c.cc.Invoke(ctx, App_Buy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) RentLand(ctx context.Context, in *RentLandRequest, opts ...grpc.CallOption) (*RentLandReply, error) {
	out := new(RentLandReply)
	err := c.cc.Invoke(ctx, App_RentLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandAddOutRate(ctx context.Context, in *LandAddOutRateRequest, opts ...grpc.CallOption) (*LandAddOutRateReply, error) {
	out := new(LandAddOutRateReply)
	err := c.cc.Invoke(ctx, App_LandAddOutRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) StakeGet(ctx context.Context, in *StakeGetRequest, opts ...grpc.CallOption) (*StakeGetReply, error) {
	out := new(StakeGetReply)
	err := c.cc.Invoke(ctx, App_StakeGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) StakeGetPlay(ctx context.Context, in *StakeGetPlayRequest, opts ...grpc.CallOption) (*StakeGetPlayReply, error) {
	out := new(StakeGetPlayReply)
	err := c.cc.Invoke(ctx, App_StakeGetPlay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlay(ctx context.Context, in *LandPlayRequest, opts ...grpc.CallOption) (*LandPlayReply, error) {
	out := new(LandPlayReply)
	err := c.cc.Invoke(ctx, App_LandPlay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlayOne(ctx context.Context, in *LandPlayOneRequest, opts ...grpc.CallOption) (*LandPlayOneReply, error) {
	out := new(LandPlayOneReply)
	err := c.cc.Invoke(ctx, App_LandPlayOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlayTwo(ctx context.Context, in *LandPlayTwoRequest, opts ...grpc.CallOption) (*LandPlayTwoReply, error) {
	out := new(LandPlayTwoReply)
	err := c.cc.Invoke(ctx, App_LandPlayTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlayThree(ctx context.Context, in *LandPlayThreeRequest, opts ...grpc.CallOption) (*LandPlayThreeReply, error) {
	out := new(LandPlayThreeReply)
	err := c.cc.Invoke(ctx, App_LandPlayThree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlayFour(ctx context.Context, in *LandPlayFourRequest, opts ...grpc.CallOption) (*LandPlayFourReply, error) {
	out := new(LandPlayFourReply)
	err := c.cc.Invoke(ctx, App_LandPlayFour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlayFive(ctx context.Context, in *LandPlayFiveRequest, opts ...grpc.CallOption) (*LandPlayFiveReply, error) {
	out := new(LandPlayFiveReply)
	err := c.cc.Invoke(ctx, App_LandPlayFive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlaySix(ctx context.Context, in *LandPlaySixRequest, opts ...grpc.CallOption) (*LandPlaySixReply, error) {
	out := new(LandPlaySixReply)
	err := c.cc.Invoke(ctx, App_LandPlaySix_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) LandPlaySeven(ctx context.Context, in *LandPlaySevenRequest, opts ...grpc.CallOption) (*LandPlaySevenReply, error) {
	out := new(LandPlaySevenReply)
	err := c.cc.Invoke(ctx, App_LandPlaySeven_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetGiw(ctx context.Context, in *SetGiwRequest, opts ...grpc.CallOption) (*SetGiwReply, error) {
	out := new(SetGiwReply)
	err := c.cc.Invoke(ctx, App_SetGiw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetGit(ctx context.Context, in *SetGitRequest, opts ...grpc.CallOption) (*SetGitReply, error) {
	out := new(SetGitReply)
	err := c.cc.Invoke(ctx, App_SetGit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetLand(ctx context.Context, in *SetLandRequest, opts ...grpc.CallOption) (*SetLandReply, error) {
	out := new(SetLandReply)
	err := c.cc.Invoke(ctx, App_SetLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) BuyLand(ctx context.Context, in *BuyLandRequest, opts ...grpc.CallOption) (*BuyLandReply, error) {
	out := new(BuyLandReply)
	err := c.cc.Invoke(ctx, App_BuyLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetBuyLand(ctx context.Context, in *GetBuyLandRequest, opts ...grpc.CallOption) (*GetBuyLandReply, error) {
	out := new(GetBuyLandReply)
	err := c.cc.Invoke(ctx, App_GetBuyLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) BuyLandRecord(ctx context.Context, in *BuyLandRecordRequest, opts ...grpc.CallOption) (*BuyLandRecordReply, error) {
	out := new(BuyLandRecordReply)
	err := c.cc.Invoke(ctx, App_BuyLandRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetBuyLand(ctx context.Context, in *SetBuyLandRequest, opts ...grpc.CallOption) (*SetBuyLandReply, error) {
	out := new(SetBuyLandReply)
	err := c.cc.Invoke(ctx, App_SetBuyLand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
// All implementations must embed UnimplementedAppServer
// for forward compatibility
type AppServer interface {
	TestSign(context.Context, *TestSignRequest) (*TestSignReply, error)
	EthAuthorize(context.Context, *EthAuthorizeRequest) (*EthAuthorizeReply, error)
	AddMessage(context.Context, *AddMessageRequest) (*AddMessageReply, error)
	// 用户信息
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoReply, error)
	// 认购信息
	UserBuy(context.Context, *UserBuyRequest) (*UserBuyReply, error)
	// 认购奖励内容
	UserBuyL(context.Context, *UserBuyLRequest) (*UserBuyLReply, error)
	// 直推列表
	UserRecommend(context.Context, *UserRecommendRequest) (*UserRecommendReply, error)
	// L1L2L3内容
	UserRecommendL(context.Context, *UserRecommendLRequest) (*UserRecommendLReply, error)
	// 粮仓列表
	UserRewardList(context.Context, *UserRewardListRequest) (*UserRewardListReply, error)
	UserTeamDepositList(context.Context, *UserTeamDepositListRequest) (*UserTeamDepositListReply, error)
	// 土地背包列表
	UserLand(context.Context, *UserLandRequest) (*UserLandReply, error)
	// 粮仓列表
	UserStakeGitRewardList(context.Context, *UserStakeGitRewardListRequest) (*UserStakeGitRewardListReply, error)
	// 粮仓列表
	UserStakeGitStakeList(context.Context, *UserStakeGitStakeListRequest) (*UserStakeGitStakeListReply, error)
	// 盲盒列表
	UserBoxList(context.Context, *UserBoxListRequest) (*UserBoxListReply, error)
	// 仓库
	UserBackList(context.Context, *UserBackListRequest) (*UserBackListReply, error)
	// 市场 种子
	UserMarketSeedList(context.Context, *UserMarketSeedListRequest) (*UserMarketSeedListReply, error)
	// 市场 土地
	UserMarketLandList(context.Context, *UserMarketLandListRequest) (*UserMarketLandListReply, error)
	// 市场 道具
	UserMarketPropList(context.Context, *UserMarketPropListRequest) (*UserMarketPropListReply, error)
	// 市场 出租
	UserMarketRentLandList(context.Context, *UserMarketRentLandListRequest) (*UserMarketRentLandListReply, error)
	// 市场 我的
	UserMyMarketList(context.Context, *UserMyMarketListRequest) (*UserMyMarketListReply, error)
	// 通知
	UserNoticeList(context.Context, *UserNoticeListRequest) (*UserNoticeListReply, error)
	// 果实放大器 获奖记录
	UserStakeRewardList(context.Context, *UserStakeRewardListRequest) (*UserStakeRewardListReply, error)
	// 首页
	UserIndexList(context.Context, *UserIndexListRequest) (*UserIndexListReply, error)
	// 排行榜
	UserOrderList(context.Context, *UserOrderListRequest) (*UserOrderListReply, error)
	UserOrderListTwo(context.Context, *UserOrderListRequest) (*UserOrderListReply, error)
	UserRankList(context.Context, *UserOrderListRequest) (*UserOrderListReply, error)
	// 提现
	BuyTwo(context.Context, *BuyTwoRequest) (*BuyTwoReply, error)
	// 提现
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawReply, error)
	// 兑换
	Exchange(context.Context, *ExchangeRequest) (*ExchangeReply, error)
	// 转账
	ToAmount(context.Context, *ToAmountRequest) (*ToAmountReply, error)
	// 合成土地
	GetLand(context.Context, *GetLandRequest) (*GetLandReply, error)
	// 粮仓的质押和赎回
	StakeGit(context.Context, *StakeGitRequest) (*StakeGitReply, error)
	// 购买盲盒
	BuyBox(context.Context, *BuyBoxRequest) (*BuyBoxReply, error)
	// 开盲盒
	OpenBox(context.Context, *OpenBoxRequest) (*OpenBoxReply, error)
	// 出售道具下架道具
	Sell(context.Context, *SellRequest) (*SellReply, error)
	// 购买道具
	Buy(context.Context, *BuyRequest) (*BuyReply, error)
	// 出租土地结束出租
	RentLand(context.Context, *RentLandRequest) (*RentLandReply, error)
	// 培育
	LandAddOutRate(context.Context, *LandAddOutRateRequest) (*LandAddOutRateReply, error)
	// 放大器质押解压
	StakeGet(context.Context, *StakeGetRequest) (*StakeGetReply, error)
	// 放大器游戏
	StakeGetPlay(context.Context, *StakeGetPlayRequest) (*StakeGetPlayReply, error)
	// 土地替换，收回
	LandPlay(context.Context, *LandPlayRequest) (*LandPlayReply, error)
	// 种植和出租的种植
	LandPlayOne(context.Context, *LandPlayOneRequest) (*LandPlayOneReply, error)
	// 收成熟植物和出租的
	LandPlayTwo(context.Context, *LandPlayTwoRequest) (*LandPlayTwoReply, error)
	// 施肥和出租的
	LandPlayThree(context.Context, *LandPlayThreeRequest) (*LandPlayThreeReply, error)
	// 杀虫和出租的
	LandPlayFour(context.Context, *LandPlayFourRequest) (*LandPlayFourReply, error)
	// 浇水和出租的
	LandPlayFive(context.Context, *LandPlayFiveRequest) (*LandPlayFiveReply, error)
	// 铲子铲别人
	LandPlaySix(context.Context, *LandPlaySixRequest) (*LandPlaySixReply, error)
	// 手套偷别人
	LandPlaySeven(context.Context, *LandPlaySevenRequest) (*LandPlaySevenReply, error)
	SetGiw(context.Context, *SetGiwRequest) (*SetGiwReply, error)
	SetGit(context.Context, *SetGitRequest) (*SetGitReply, error)
	SetLand(context.Context, *SetLandRequest) (*SetLandReply, error)
	BuyLand(context.Context, *BuyLandRequest) (*BuyLandReply, error)
	GetBuyLand(context.Context, *GetBuyLandRequest) (*GetBuyLandReply, error)
	BuyLandRecord(context.Context, *BuyLandRecordRequest) (*BuyLandRecordReply, error)
	SetBuyLand(context.Context, *SetBuyLandRequest) (*SetBuyLandReply, error)
	mustEmbedUnimplementedAppServer()
}

// UnimplementedAppServer must be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (UnimplementedAppServer) TestSign(context.Context, *TestSignRequest) (*TestSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestSign not implemented")
}
func (UnimplementedAppServer) EthAuthorize(context.Context, *EthAuthorizeRequest) (*EthAuthorizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EthAuthorize not implemented")
}
func (UnimplementedAppServer) AddMessage(context.Context, *AddMessageRequest) (*AddMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedAppServer) UserInfo(context.Context, *UserInfoRequest) (*UserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedAppServer) UserBuy(context.Context, *UserBuyRequest) (*UserBuyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserBuy not implemented")
}
func (UnimplementedAppServer) UserBuyL(context.Context, *UserBuyLRequest) (*UserBuyLReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserBuyL not implemented")
}
func (UnimplementedAppServer) UserRecommend(context.Context, *UserRecommendRequest) (*UserRecommendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRecommend not implemented")
}
func (UnimplementedAppServer) UserRecommendL(context.Context, *UserRecommendLRequest) (*UserRecommendLReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRecommendL not implemented")
}
func (UnimplementedAppServer) UserRewardList(context.Context, *UserRewardListRequest) (*UserRewardListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRewardList not implemented")
}
func (UnimplementedAppServer) UserTeamDepositList(context.Context, *UserTeamDepositListRequest) (*UserTeamDepositListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserTeamDepositList not implemented")
}
func (UnimplementedAppServer) UserLand(context.Context, *UserLandRequest) (*UserLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLand not implemented")
}
func (UnimplementedAppServer) UserStakeGitRewardList(context.Context, *UserStakeGitRewardListRequest) (*UserStakeGitRewardListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserStakeGitRewardList not implemented")
}
func (UnimplementedAppServer) UserStakeGitStakeList(context.Context, *UserStakeGitStakeListRequest) (*UserStakeGitStakeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserStakeGitStakeList not implemented")
}
func (UnimplementedAppServer) UserBoxList(context.Context, *UserBoxListRequest) (*UserBoxListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserBoxList not implemented")
}
func (UnimplementedAppServer) UserBackList(context.Context, *UserBackListRequest) (*UserBackListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserBackList not implemented")
}
func (UnimplementedAppServer) UserMarketSeedList(context.Context, *UserMarketSeedListRequest) (*UserMarketSeedListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMarketSeedList not implemented")
}
func (UnimplementedAppServer) UserMarketLandList(context.Context, *UserMarketLandListRequest) (*UserMarketLandListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMarketLandList not implemented")
}
func (UnimplementedAppServer) UserMarketPropList(context.Context, *UserMarketPropListRequest) (*UserMarketPropListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMarketPropList not implemented")
}
func (UnimplementedAppServer) UserMarketRentLandList(context.Context, *UserMarketRentLandListRequest) (*UserMarketRentLandListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMarketRentLandList not implemented")
}
func (UnimplementedAppServer) UserMyMarketList(context.Context, *UserMyMarketListRequest) (*UserMyMarketListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMyMarketList not implemented")
}
func (UnimplementedAppServer) UserNoticeList(context.Context, *UserNoticeListRequest) (*UserNoticeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserNoticeList not implemented")
}
func (UnimplementedAppServer) UserStakeRewardList(context.Context, *UserStakeRewardListRequest) (*UserStakeRewardListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserStakeRewardList not implemented")
}
func (UnimplementedAppServer) UserIndexList(context.Context, *UserIndexListRequest) (*UserIndexListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserIndexList not implemented")
}
func (UnimplementedAppServer) UserOrderList(context.Context, *UserOrderListRequest) (*UserOrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderList not implemented")
}
func (UnimplementedAppServer) UserOrderListTwo(context.Context, *UserOrderListRequest) (*UserOrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderListTwo not implemented")
}
func (UnimplementedAppServer) UserRankList(context.Context, *UserOrderListRequest) (*UserOrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRankList not implemented")
}
func (UnimplementedAppServer) BuyTwo(context.Context, *BuyTwoRequest) (*BuyTwoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyTwo not implemented")
}
func (UnimplementedAppServer) Withdraw(context.Context, *WithdrawRequest) (*WithdrawReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedAppServer) Exchange(context.Context, *ExchangeRequest) (*ExchangeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedAppServer) ToAmount(context.Context, *ToAmountRequest) (*ToAmountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToAmount not implemented")
}
func (UnimplementedAppServer) GetLand(context.Context, *GetLandRequest) (*GetLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLand not implemented")
}
func (UnimplementedAppServer) StakeGit(context.Context, *StakeGitRequest) (*StakeGitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakeGit not implemented")
}
func (UnimplementedAppServer) BuyBox(context.Context, *BuyBoxRequest) (*BuyBoxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyBox not implemented")
}
func (UnimplementedAppServer) OpenBox(context.Context, *OpenBoxRequest) (*OpenBoxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenBox not implemented")
}
func (UnimplementedAppServer) Sell(context.Context, *SellRequest) (*SellReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sell not implemented")
}
func (UnimplementedAppServer) Buy(context.Context, *BuyRequest) (*BuyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}
func (UnimplementedAppServer) RentLand(context.Context, *RentLandRequest) (*RentLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentLand not implemented")
}
func (UnimplementedAppServer) LandAddOutRate(context.Context, *LandAddOutRateRequest) (*LandAddOutRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandAddOutRate not implemented")
}
func (UnimplementedAppServer) StakeGet(context.Context, *StakeGetRequest) (*StakeGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakeGet not implemented")
}
func (UnimplementedAppServer) StakeGetPlay(context.Context, *StakeGetPlayRequest) (*StakeGetPlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakeGetPlay not implemented")
}
func (UnimplementedAppServer) LandPlay(context.Context, *LandPlayRequest) (*LandPlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlay not implemented")
}
func (UnimplementedAppServer) LandPlayOne(context.Context, *LandPlayOneRequest) (*LandPlayOneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlayOne not implemented")
}
func (UnimplementedAppServer) LandPlayTwo(context.Context, *LandPlayTwoRequest) (*LandPlayTwoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlayTwo not implemented")
}
func (UnimplementedAppServer) LandPlayThree(context.Context, *LandPlayThreeRequest) (*LandPlayThreeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlayThree not implemented")
}
func (UnimplementedAppServer) LandPlayFour(context.Context, *LandPlayFourRequest) (*LandPlayFourReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlayFour not implemented")
}
func (UnimplementedAppServer) LandPlayFive(context.Context, *LandPlayFiveRequest) (*LandPlayFiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlayFive not implemented")
}
func (UnimplementedAppServer) LandPlaySix(context.Context, *LandPlaySixRequest) (*LandPlaySixReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlaySix not implemented")
}
func (UnimplementedAppServer) LandPlaySeven(context.Context, *LandPlaySevenRequest) (*LandPlaySevenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LandPlaySeven not implemented")
}
func (UnimplementedAppServer) SetGiw(context.Context, *SetGiwRequest) (*SetGiwReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGiw not implemented")
}
func (UnimplementedAppServer) SetGit(context.Context, *SetGitRequest) (*SetGitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGit not implemented")
}
func (UnimplementedAppServer) SetLand(context.Context, *SetLandRequest) (*SetLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLand not implemented")
}
func (UnimplementedAppServer) BuyLand(context.Context, *BuyLandRequest) (*BuyLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyLand not implemented")
}
func (UnimplementedAppServer) GetBuyLand(context.Context, *GetBuyLandRequest) (*GetBuyLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuyLand not implemented")
}
func (UnimplementedAppServer) BuyLandRecord(context.Context, *BuyLandRecordRequest) (*BuyLandRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyLandRecord not implemented")
}
func (UnimplementedAppServer) SetBuyLand(context.Context, *SetBuyLandRequest) (*SetBuyLandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBuyLand not implemented")
}
func (UnimplementedAppServer) mustEmbedUnimplementedAppServer() {}

// UnsafeAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServer will
// result in compilation errors.
type UnsafeAppServer interface {
	mustEmbedUnimplementedAppServer()
}

func RegisterAppServer(s grpc.ServiceRegistrar, srv AppServer) {
	s.RegisterService(&App_ServiceDesc, srv)
}

func _App_TestSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).TestSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_TestSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).TestSign(ctx, req.(*TestSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_EthAuthorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EthAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).EthAuthorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_EthAuthorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).EthAuthorize(ctx, req.(*EthAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserBuy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserBuy(ctx, req.(*UserBuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserBuyL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBuyLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserBuyL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserBuyL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserBuyL(ctx, req.(*UserBuyLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserRecommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserRecommend(ctx, req.(*UserRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserRecommendL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRecommendLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserRecommendL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserRecommendL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserRecommendL(ctx, req.(*UserRecommendLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserRewardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRewardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserRewardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserRewardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserRewardList(ctx, req.(*UserRewardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserTeamDepositList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTeamDepositListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserTeamDepositList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserTeamDepositList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserTeamDepositList(ctx, req.(*UserTeamDepositListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserLand(ctx, req.(*UserLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserStakeGitRewardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserStakeGitRewardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserStakeGitRewardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserStakeGitRewardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserStakeGitRewardList(ctx, req.(*UserStakeGitRewardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserStakeGitStakeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserStakeGitStakeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserStakeGitStakeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserStakeGitStakeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserStakeGitStakeList(ctx, req.(*UserStakeGitStakeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserBoxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBoxListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserBoxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserBoxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserBoxList(ctx, req.(*UserBoxListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserBackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBackListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserBackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserBackList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserBackList(ctx, req.(*UserBackListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserMarketSeedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMarketSeedListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserMarketSeedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserMarketSeedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserMarketSeedList(ctx, req.(*UserMarketSeedListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserMarketLandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMarketLandListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserMarketLandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserMarketLandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserMarketLandList(ctx, req.(*UserMarketLandListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserMarketPropList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMarketPropListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserMarketPropList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserMarketPropList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserMarketPropList(ctx, req.(*UserMarketPropListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserMarketRentLandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMarketRentLandListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserMarketRentLandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserMarketRentLandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserMarketRentLandList(ctx, req.(*UserMarketRentLandListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserMyMarketList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMyMarketListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserMyMarketList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserMyMarketList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserMyMarketList(ctx, req.(*UserMyMarketListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserNoticeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNoticeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserNoticeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserNoticeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserNoticeList(ctx, req.(*UserNoticeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserStakeRewardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserStakeRewardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserStakeRewardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserStakeRewardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserStakeRewardList(ctx, req.(*UserStakeRewardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserIndexList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIndexListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserIndexList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserIndexList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserIndexList(ctx, req.(*UserIndexListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserOrderList(ctx, req.(*UserOrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserOrderListTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserOrderListTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserOrderListTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserOrderListTwo(ctx, req.(*UserOrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UserRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UserRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UserRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UserRankList(ctx, req.(*UserOrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_BuyTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).BuyTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_BuyTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).BuyTwo(ctx, req.(*BuyTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Exchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ToAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ToAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_ToAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ToAmount(ctx, req.(*ToAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetLand(ctx, req.(*GetLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_StakeGit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeGitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).StakeGit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_StakeGit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).StakeGit(ctx, req.(*StakeGitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_BuyBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).BuyBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_BuyBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).BuyBox(ctx, req.(*BuyBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_OpenBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).OpenBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_OpenBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).OpenBox(ctx, req.(*OpenBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Sell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Sell(ctx, req.(*SellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Buy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_RentLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).RentLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_RentLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).RentLand(ctx, req.(*RentLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandAddOutRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandAddOutRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandAddOutRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandAddOutRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandAddOutRate(ctx, req.(*LandAddOutRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_StakeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).StakeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_StakeGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).StakeGet(ctx, req.(*StakeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_StakeGetPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeGetPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).StakeGetPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_StakeGetPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).StakeGetPlay(ctx, req.(*StakeGetPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlay(ctx, req.(*LandPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlayOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlayOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlayOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlayOne(ctx, req.(*LandPlayOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlayTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlayTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlayTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlayTwo(ctx, req.(*LandPlayTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlayThree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayThreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlayThree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlayThree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlayThree(ctx, req.(*LandPlayThreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlayFour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayFourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlayFour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlayFour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlayFour(ctx, req.(*LandPlayFourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlayFive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlayFiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlayFive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlayFive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlayFive(ctx, req.(*LandPlayFiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlaySix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlaySixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlaySix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlaySix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlaySix(ctx, req.(*LandPlaySixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_LandPlaySeven_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandPlaySevenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).LandPlaySeven(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_LandPlaySeven_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).LandPlaySeven(ctx, req.(*LandPlaySevenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetGiw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGiwRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetGiw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetGiw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetGiw(ctx, req.(*SetGiwRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetGit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetGit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetGit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetGit(ctx, req.(*SetGitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetLand(ctx, req.(*SetLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_BuyLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).BuyLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_BuyLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).BuyLand(ctx, req.(*BuyLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetBuyLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuyLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetBuyLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetBuyLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetBuyLand(ctx, req.(*GetBuyLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_BuyLandRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyLandRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).BuyLandRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_BuyLandRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).BuyLandRecord(ctx, req.(*BuyLandRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetBuyLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBuyLandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetBuyLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetBuyLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetBuyLand(ctx, req.(*SetBuyLandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// App_ServiceDesc is the grpc.ServiceDesc for App service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var App_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.app.v1.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestSign",
			Handler:    _App_TestSign_Handler,
		},
		{
			MethodName: "EthAuthorize",
			Handler:    _App_EthAuthorize_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _App_AddMessage_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _App_UserInfo_Handler,
		},
		{
			MethodName: "UserBuy",
			Handler:    _App_UserBuy_Handler,
		},
		{
			MethodName: "UserBuyL",
			Handler:    _App_UserBuyL_Handler,
		},
		{
			MethodName: "UserRecommend",
			Handler:    _App_UserRecommend_Handler,
		},
		{
			MethodName: "UserRecommendL",
			Handler:    _App_UserRecommendL_Handler,
		},
		{
			MethodName: "UserRewardList",
			Handler:    _App_UserRewardList_Handler,
		},
		{
			MethodName: "UserTeamDepositList",
			Handler:    _App_UserTeamDepositList_Handler,
		},
		{
			MethodName: "UserLand",
			Handler:    _App_UserLand_Handler,
		},
		{
			MethodName: "UserStakeGitRewardList",
			Handler:    _App_UserStakeGitRewardList_Handler,
		},
		{
			MethodName: "UserStakeGitStakeList",
			Handler:    _App_UserStakeGitStakeList_Handler,
		},
		{
			MethodName: "UserBoxList",
			Handler:    _App_UserBoxList_Handler,
		},
		{
			MethodName: "UserBackList",
			Handler:    _App_UserBackList_Handler,
		},
		{
			MethodName: "UserMarketSeedList",
			Handler:    _App_UserMarketSeedList_Handler,
		},
		{
			MethodName: "UserMarketLandList",
			Handler:    _App_UserMarketLandList_Handler,
		},
		{
			MethodName: "UserMarketPropList",
			Handler:    _App_UserMarketPropList_Handler,
		},
		{
			MethodName: "UserMarketRentLandList",
			Handler:    _App_UserMarketRentLandList_Handler,
		},
		{
			MethodName: "UserMyMarketList",
			Handler:    _App_UserMyMarketList_Handler,
		},
		{
			MethodName: "UserNoticeList",
			Handler:    _App_UserNoticeList_Handler,
		},
		{
			MethodName: "UserStakeRewardList",
			Handler:    _App_UserStakeRewardList_Handler,
		},
		{
			MethodName: "UserIndexList",
			Handler:    _App_UserIndexList_Handler,
		},
		{
			MethodName: "UserOrderList",
			Handler:    _App_UserOrderList_Handler,
		},
		{
			MethodName: "UserOrderListTwo",
			Handler:    _App_UserOrderListTwo_Handler,
		},
		{
			MethodName: "UserRankList",
			Handler:    _App_UserRankList_Handler,
		},
		{
			MethodName: "BuyTwo",
			Handler:    _App_BuyTwo_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _App_Withdraw_Handler,
		},
		{
			MethodName: "Exchange",
			Handler:    _App_Exchange_Handler,
		},
		{
			MethodName: "ToAmount",
			Handler:    _App_ToAmount_Handler,
		},
		{
			MethodName: "GetLand",
			Handler:    _App_GetLand_Handler,
		},
		{
			MethodName: "StakeGit",
			Handler:    _App_StakeGit_Handler,
		},
		{
			MethodName: "BuyBox",
			Handler:    _App_BuyBox_Handler,
		},
		{
			MethodName: "OpenBox",
			Handler:    _App_OpenBox_Handler,
		},
		{
			MethodName: "Sell",
			Handler:    _App_Sell_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _App_Buy_Handler,
		},
		{
			MethodName: "RentLand",
			Handler:    _App_RentLand_Handler,
		},
		{
			MethodName: "LandAddOutRate",
			Handler:    _App_LandAddOutRate_Handler,
		},
		{
			MethodName: "StakeGet",
			Handler:    _App_StakeGet_Handler,
		},
		{
			MethodName: "StakeGetPlay",
			Handler:    _App_StakeGetPlay_Handler,
		},
		{
			MethodName: "LandPlay",
			Handler:    _App_LandPlay_Handler,
		},
		{
			MethodName: "LandPlayOne",
			Handler:    _App_LandPlayOne_Handler,
		},
		{
			MethodName: "LandPlayTwo",
			Handler:    _App_LandPlayTwo_Handler,
		},
		{
			MethodName: "LandPlayThree",
			Handler:    _App_LandPlayThree_Handler,
		},
		{
			MethodName: "LandPlayFour",
			Handler:    _App_LandPlayFour_Handler,
		},
		{
			MethodName: "LandPlayFive",
			Handler:    _App_LandPlayFive_Handler,
		},
		{
			MethodName: "LandPlaySix",
			Handler:    _App_LandPlaySix_Handler,
		},
		{
			MethodName: "LandPlaySeven",
			Handler:    _App_LandPlaySeven_Handler,
		},
		{
			MethodName: "SetGiw",
			Handler:    _App_SetGiw_Handler,
		},
		{
			MethodName: "SetGit",
			Handler:    _App_SetGit_Handler,
		},
		{
			MethodName: "SetLand",
			Handler:    _App_SetLand_Handler,
		},
		{
			MethodName: "BuyLand",
			Handler:    _App_BuyLand_Handler,
		},
		{
			MethodName: "GetBuyLand",
			Handler:    _App_GetBuyLand_Handler,
		},
		{
			MethodName: "BuyLandRecord",
			Handler:    _App_BuyLandRecord_Handler,
		},
		{
			MethodName: "SetBuyLand",
			Handler:    _App_SetBuyLand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/app/v1/app.proto",
}
