-- 全部348个非自增字段设置明确默认值；先选择已恢复的目标数据库。
-- 若旧版表缺stake_git.sell_amount，先执行09补列；本文件不负责补缺表/缺列。
-- 最新08空库建表已包含本策略，首次导入08不需要再执行本文件。
-- 只ALTER COLUMN SET DEFAULT，不改类型、NULL约束、索引、注释，不更新已有记录。
-- 保留模型业务默认值；14个原DEFAULT NULL字段改成空串或CURRENT_TIMESTAMP。
-- 自增主键由AUTO_INCREMENT生成，不能另加普通DEFAULT；共38个自增列。
-- 默认值处理省略列/使用DEFAULT的INSERT；显式传NULL或非法值不由默认值纠正。
SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE `user`
  ALTER COLUMN `address` SET DEFAULT '',
  ALTER COLUMN `level` SET DEFAULT 0,
  ALTER COLUMN `giw` SET DEFAULT 0,
  ALTER COLUMN `giw_add` SET DEFAULT 0,
  ALTER COLUMN `git` SET DEFAULT 0,
  ALTER COLUMN `total` SET DEFAULT 0,
  ALTER COLUMN `total_one` SET DEFAULT 0,
  ALTER COLUMN `total_two` SET DEFAULT 0,
  ALTER COLUMN `total_three` SET DEFAULT 0,
  ALTER COLUMN `reward_one` SET DEFAULT 0,
  ALTER COLUMN `reward_two` SET DEFAULT 0,
  ALTER COLUMN `reward_three` SET DEFAULT 0,
  ALTER COLUMN `reward_two_one` SET DEFAULT 0,
  ALTER COLUMN `reward_two_two` SET DEFAULT 0,
  ALTER COLUMN `reward_two_three` SET DEFAULT 0,
  ALTER COLUMN `reward_three_one` SET DEFAULT 0,
  ALTER COLUMN `reward_three_two` SET DEFAULT 0,
  ALTER COLUMN `reward_three_three` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `location` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `recommend` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `recommend_two` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `area` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `area_two` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `all` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `all_num` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `amount_get` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `amount_usdt` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `amount_usdt_total` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `my_total_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `my_total_amount_new` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_num` SET DEFAULT 0,
  ALTER COLUMN `vip` SET DEFAULT 0,
  ALTER COLUMN `vip_admin` SET DEFAULT 0,
  ALTER COLUMN `lock_use` SET DEFAULT 0,
  ALTER COLUMN `lock_reward` SET DEFAULT 0,
  ALTER COLUMN `usdt_two` SET DEFAULT 0,
  ALTER COLUMN `giw_two` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `can_sell` SET DEFAULT 0,
  ALTER COLUMN `can_rent` SET DEFAULT 0,
  ALTER COLUMN `can_land` SET DEFAULT 0,
  ALTER COLUMN `withdraw_max` SET DEFAULT 0,
  ALTER COLUMN `can_sell_prop` SET DEFAULT 0,
  ALTER COLUMN `can_play_add` SET DEFAULT 0,
  ALTER COLUMN `can_play_six` SET DEFAULT 0,
  ALTER COLUMN `git_new` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `git_new_new` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `one` SET DEFAULT 0,
  ALTER COLUMN `two` SET DEFAULT 0,
  ALTER COLUMN `three` SET DEFAULT 0,
  ALTER COLUMN `ispay_amount` SET DEFAULT 0,
  ALTER COLUMN `stake_ispay_amount` SET DEFAULT 0,
  ALTER COLUMN `open_box_amount` SET DEFAULT 0,
  ALTER COLUMN `land_count` SET DEFAULT 0,
  ALTER COLUMN `last_reward_total` SET DEFAULT 0,
  ALTER COLUMN `land_reward` SET DEFAULT 0,
  ALTER COLUMN `recommend_one` SET DEFAULT 0;

ALTER TABLE `user_recommend`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `recommend_code` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `admin`
  ALTER COLUMN `account` SET DEFAULT '',
  ALTER COLUMN `password` SET DEFAULT '',
  ALTER COLUMN `type` SET DEFAULT '';

ALTER TABLE `admin_set_balance`
  ALTER COLUMN `address` SET DEFAULT '',
  ALTER COLUMN `coin` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `config`
  ALTER COLUMN `name` SET DEFAULT '',
  ALTER COLUMN `key_name` SET DEFAULT '',
  ALTER COLUMN `value` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `notice`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `notice_content` SET DEFAULT '',
  ALTER COLUMN `notice_content_two` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `message`
  ALTER COLUMN `content` SET DEFAULT '',
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `admin_message`
  ALTER COLUMN `content` SET DEFAULT '',
  ALTER COLUMN `content_two` SET DEFAULT '',
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `land`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `level` SET DEFAULT 1,
  ALTER COLUMN `out_put_rate` SET DEFAULT 100.00000000000000000000,
  ALTER COLUMN `rent_out_put_rate` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `max_health` SET DEFAULT 100,
  ALTER COLUMN `per_health` SET DEFAULT 10,
  ALTER COLUMN `limit_date` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `location_num` SET DEFAULT 0,
  ALTER COLUMN `one` SET DEFAULT 1,
  ALTER COLUMN `two` SET DEFAULT 1,
  ALTER COLUMN `three` SET DEFAULT 1,
  ALTER COLUMN `sell_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `admin_add` SET DEFAULT 0,
  ALTER COLUMN `location_user_id` SET DEFAULT 0,
  ALTER COLUMN `can_reward` SET DEFAULT 0;

ALTER TABLE `land_user_use`
  ALTER COLUMN `land_id` SET DEFAULT 0,
  ALTER COLUMN `level` SET DEFAULT 0,
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `owner_user_id` SET DEFAULT 0,
  ALTER COLUMN `seed_id` SET DEFAULT 0,
  ALTER COLUMN `seed_type_id` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 1,
  ALTER COLUMN `begin_time` SET DEFAULT 0,
  ALTER COLUMN `total_time` SET DEFAULT 0,
  ALTER COLUMN `over_time` SET DEFAULT 0,
  ALTER COLUMN `out_max_num` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_num` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `insect_status` SET DEFAULT 1,
  ALTER COLUMN `out_sub_num` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `steal_num` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `stop_status` SET DEFAULT 1,
  ALTER COLUMN `stop_time` SET DEFAULT 0,
  ALTER COLUMN `sub_time` SET DEFAULT 0,
  ALTER COLUMN `use_chan` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `one` SET DEFAULT 0,
  ALTER COLUMN `two` SET DEFAULT 0,
  ALTER COLUMN `is_use_other` SET DEFAULT 0;

ALTER TABLE `seed`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `seed_id` SET DEFAULT 0,
  ALTER COLUMN `name` SET DEFAULT '1',
  ALTER COLUMN `out_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_over_time` SET DEFAULT 0,
  ALTER COLUMN `out_max_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_min_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `sell_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `admin_add` SET DEFAULT 0;

ALTER TABLE `prop`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 1,
  ALTER COLUMN `prop_type` SET DEFAULT 0,
  ALTER COLUMN `one_one` SET DEFAULT 20,
  ALTER COLUMN `one_two` SET DEFAULT 14400,
  ALTER COLUMN `two_one` SET DEFAULT 7,
  ALTER COLUMN `two_two` SET DEFAULT 20.00000000000000000000,
  ALTER COLUMN `three_one` SET DEFAULT 1,
  ALTER COLUMN `four_one` SET DEFAULT 10,
  ALTER COLUMN `five_one` SET DEFAULT 20,
  ALTER COLUMN `sell_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `admin_add` SET DEFAULT 0;

ALTER TABLE `land_info`
  ALTER COLUMN `level` SET DEFAULT 1,
  ALTER COLUMN `out_put_rate_max` SET DEFAULT 100.00000000000000000000,
  ALTER COLUMN `out_put_rate_min` SET DEFAULT 100.00000000000000000000,
  ALTER COLUMN `rent_out_put_rate_max` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `max_health` SET DEFAULT 100,
  ALTER COLUMN `per_health` SET DEFAULT 10,
  ALTER COLUMN `limit_date_max` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `seed_info`
  ALTER COLUMN `name` SET DEFAULT '1',
  ALTER COLUMN `out_min_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_max_amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `get_rate` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `out_over_time` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `prop_info`
  ALTER COLUMN `prop_type` SET DEFAULT 0,
  ALTER COLUMN `one_one` SET DEFAULT 20,
  ALTER COLUMN `one_two` SET DEFAULT 14400,
  ALTER COLUMN `two_one` SET DEFAULT 7,
  ALTER COLUMN `two_two` SET DEFAULT 20.00000000000000000000,
  ALTER COLUMN `three_one` SET DEFAULT 7,
  ALTER COLUMN `four_one` SET DEFAULT 7,
  ALTER COLUMN `five_one` SET DEFAULT 20,
  ALTER COLUMN `get_rate` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP(3),
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `random_seeds`
  ALTER COLUMN `scene` SET DEFAULT 0,
  ALTER COLUMN `seed_value` SET DEFAULT 0,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP(3),
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `box_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `num` SET DEFAULT 0,
  ALTER COLUMN `good_id` SET DEFAULT 0,
  ALTER COLUMN `good_type` SET DEFAULT 0,
  ALTER COLUMN `content` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `market`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `good_id` SET DEFAULT 0,
  ALTER COLUMN `good_type` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.00000000000000000000,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `get_user_id` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `buy_land`
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `status` SET DEFAULT 1,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `amount_two` SET DEFAULT 0.0,
  ALTER COLUMN `limit` SET DEFAULT 0,
  ALTER COLUMN `level` SET DEFAULT 1;

ALTER TABLE `buy_land_record`
  ALTER COLUMN `buy_land_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `status` SET DEFAULT 1,
  ALTER COLUMN `user_id` SET DEFAULT 0;

ALTER TABLE `reward`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `reason` SET DEFAULT 0,
  ALTER COLUMN `one` SET DEFAULT 0,
  ALTER COLUMN `two` SET DEFAULT 0,
  ALTER COLUMN `three` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `reward_two`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `reason` SET DEFAULT 0,
  ALTER COLUMN `one` SET DEFAULT 0,
  ALTER COLUMN `two` SET DEFAULT 0,
  ALTER COLUMN `three` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `four` SET DEFAULT '',
  ALTER COLUMN `five` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `reward_four`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `reason` SET DEFAULT 0,
  ALTER COLUMN `one` SET DEFAULT 0,
  ALTER COLUMN `two` SET DEFAULT 0,
  ALTER COLUMN `three` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_get`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 1,
  ALTER COLUMN `stake_rate` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_get_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `stake_rate` SET DEFAULT 0.0,
  ALTER COLUMN `total` SET DEFAULT 0.0,
  ALTER COLUMN `stake_type` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_get_play_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `reward` SET DEFAULT 0.0,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_get_total`
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `balance` SET DEFAULT 0.0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_git`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `reward` SET DEFAULT 0.0,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `sell_amount` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `stake_git_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `amount_two` SET DEFAULT 0.0,
  ALTER COLUMN `stake_type` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `day` SET DEFAULT 0,
  ALTER COLUMN `price` SET DEFAULT 0.0;

ALTER TABLE `stake_git_record_ispay`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `amount_two` SET DEFAULT 0.0,
  ALTER COLUMN `stake_type` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `day` SET DEFAULT 0,
  ALTER COLUMN `price` SET DEFAULT 0.0;

ALTER TABLE `stake_git_record_ispay_queue`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0.0,
  ALTER COLUMN `amount_two` SET DEFAULT 0.0,
  ALTER COLUMN `amount_three` SET DEFAULT 0.0,
  ALTER COLUMN `stake_type` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `day` SET DEFAULT 0,
  ALTER COLUMN `price` SET DEFAULT 0.0;

ALTER TABLE `withdraw`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `rel_amount` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 'default',
  ALTER COLUMN `amount_float` SET DEFAULT 0,
  ALTER COLUMN `rel_amount_float` SET DEFAULT 0,
  ALTER COLUMN `coin` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `exchange`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount_float` SET DEFAULT 0,
  ALTER COLUMN `rel_amount_float` SET DEFAULT 0,
  ALTER COLUMN `amount_float_usdt` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `exchange_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `git` SET DEFAULT 0,
  ALTER COLUMN `giw` SET DEFAULT 0,
  ALTER COLUMN `fee` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `eth_record`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `last` SET DEFAULT 0,
  ALTER COLUMN `address` SET DEFAULT 'default',
  ALTER COLUMN `coin` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `amount_float` SET DEFAULT 0;

ALTER TABLE `eth_record_two`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `last` SET DEFAULT 0,
  ALTER COLUMN `address` SET DEFAULT 'default',
  ALTER COLUMN `coin` SET DEFAULT '',
  ALTER COLUMN `recommend_code` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `eth_record_three`
  ALTER COLUMN `user_id` SET DEFAULT 0,
  ALTER COLUMN `amount` SET DEFAULT 0,
  ALTER COLUMN `amount_biw` SET DEFAULT 0,
  ALTER COLUMN `last` SET DEFAULT 0,
  ALTER COLUMN `address` SET DEFAULT 'default',
  ALTER COLUMN `coin` SET DEFAULT '',
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `price_change`
  ALTER COLUMN `price` SET DEFAULT 0,
  ALTER COLUMN `price_new` SET DEFAULT 0,
  ALTER COLUMN `status` SET DEFAULT 0,
  ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;

-- 默认值检查：应返回0行；排除自增主键。
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME IN ('user','user_recommend','admin','admin_set_balance','config','notice','message','admin_message','land','land_user_use','seed','prop','land_info','seed_info','prop_info','random_seeds','box_record','market','buy_land','buy_land_record','reward','reward_two','reward_four','stake_get','stake_get_record','stake_get_play_record','stake_get_total','stake_git','stake_git_record','stake_git_record_ispay','stake_git_record_ispay_queue','withdraw','exchange','exchange_record','eth_record','eth_record_two','eth_record_three','price_change')
  AND EXTRA NOT LIKE '%auto_increment%' AND COLUMN_DEFAULT IS NULL
ORDER BY TABLE_NAME, ORDINAL_POSITION;
